name: Feature Request
description: Suggest an idea or enhancement for Dislo
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thank you for suggesting an enhancement for Dislo! Please fill out the following details to help us understand your request.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature or enhancement you are requesting.
      placeholder: e.g., Add support for custom authentication backends
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important? What problem does it solve?
      placeholder: Explain the use case or problem this feature addresses.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or how you imagine this feature working.
      placeholder: Provide details, examples, or pseudocode if possible.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: List any alternatives you've tried or considered.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here.
      placeholder: Any other information?
    validations:
      required: false