name: Publish Helm Chart

on:
  push:
    branches: [ "main" ]
    paths:
      - 'chart/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Helm chart to GHCR
        run: |
          helm package chart
          helm push *.tgz oci://ghcr.io/${{ github.repository_owner }}/charts