name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
